# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Project Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check typos on source files
        uses: dotanuki-labs/github-actions/quality/typos@main

      - name: Lint Markdown files
        uses: dotanuki-labs/github-actions/quality/markdown@main

      - name: Check MIT license on source files
        uses: dotanuki-labs/github-actions/foss/check-licenses@main
        with:
          file-patterns: "*.sh,*.yml"
          license: "mit"

  acceptance-tests:
    needs: quality-checks
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Test scanning standalone Android apk
        run: ./tests/pocketcasts-android.sh
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_POCKETCASTS_ANDROID_KEY }}

      - name: Test scanning standalone iOS xcarchive
        run: ./tests/pocketcasts-ios.sh
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_POCKETCASTS_IOS_KEY }}

      - name: Test scanning iOS ipa plus dSyms
        run: ./tests/bitwarden-ios.sh
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_BITWARDEN_IOS_KEY }}

      - name: Test scanning Android apk plus mappings
        run: ./tests/cromite-android.sh
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_CROMITE_ANDROID_KEY }}

  component-tests:
    needs: acceptance-tests
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Prepares fixtures
        run: ./tests/fixtures.sh

      - name: Component test for iOS GHA
        uses: ./
        with:
          archive-file: .tmp/pocket-casts-ios.xcarchive
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_POCKETCASTS_IOS_KEY }}

      - name: Component test for Android GHA
        uses: ./
        with:
          archive-file: .tmp/pocket-casts-android.apk
          wait-for-summary: true
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_DOTANUKI_POCKETCASTS_ANDROID_KEY }}
